import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile as readFsFile, writeFile, rm, stat, cp } from 'node:fs/promises';
import os from 'node:os'; import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
import { resolveManagedArtifact } from '../lib/diagram/path-policy.mjs';
import { computeReleaseVerification, computeReleaseInputState, launchManagedSession, RELEASE_CONTROL_INPUTS, runDiagramCommand, startSessionWorker } from '../lib/diagram.mjs';
import { installRuntime } from '../lib/diagram/installer.mjs';
import { createInstallPlan } from '../lib/diagram/install-plan.mjs';
import { callSessionControl, startSessionControl, writeSessionRecord } from '../lib/diagram/lifecycle.mjs';
import { readFile } from 'node:fs/promises';
const repo=path.resolve(import.meta.dirname,'..');

async function buildAuditedWebappFixture() {
  const manifest=JSON.parse(await readFsFile(path.join(repo,'core/runtimes/drawio/manifest.json')));const artifact=manifest.artifacts.drawioWebapp;
  const cache=path.join(repo,'.cache/specline-diagram',`drawio-${artifact.version}`);const archive=path.join(cache,'draw.war');const webapp=path.join(cache,'webapp');
  await mkdir(cache,{recursive:true});let valid=false;try{valid=createHash('sha256').update(await readFsFile(archive)).digest('hex')===artifact.sha256}catch{}
  if(!valid){let response;let lastError;for(let attempt=0;attempt<4;attempt++){try{response=await fetch(artifact.url,{signal:AbortSignal.timeout(120000)});if(response.ok)break;lastError=new Error(`HTTP ${response.status}`)}catch(error){lastError=error}await new Promise(r=>setTimeout(r,500*2**attempt));}if(!response?.ok)throw new Error(`DRAWIO_FIXTURE_DOWNLOAD_FAILED:${lastError?.message}`);const bytes=Buffer.from(await response.arrayBuffer());const digest=createHash('sha256').update(bytes).digest('hex');if(digest!==artifact.sha256)throw new Error(`DRAWIO_FIXTURE_CHECKSUM_MISMATCH:${digest}`);await writeFile(archive,bytes);await rm(webapp,{recursive:true,force:true});}
  if(!(await stat(path.join(webapp,'index.html')).catch(()=>null))){await mkdir(webapp,{recursive:true});await execFileAsync('unzip',['-q','-o',archive,'-d',webapp]);}
  return webapp;
}

test('production verifier rejects traversal before mutation',async()=>{const project=await mkdtemp(path.join(os.tmpdir(),'diagram-prod-')); await assert.rejects(async()=>resolveManagedArtifact({projectRoot:project,slug:'../escape',extension:'.drawio'}),e=>e.code==='INVALID_SLUG');});
test('production release inputs are digest-bound and release is verified',async()=>{const root=path.join(repo,'core/runtimes/drawio');const manifest=JSON.parse(await readFile(path.join(root,'manifest.json')));const closure=JSON.parse(await readFile(path.join(root,'dependency-lock.json')));const state=await computeReleaseVerification(manifest,{packageRoot:repo,closure});assert.equal(state.releaseInputs.complete,true);assert.match(state.releaseInputs.bundleDigest,/^[a-f0-9]{64}$/);assert.equal(state.releaseInputs.traceBound,true);assert.equal(manifest.offlineTrace.releaseInputDigest,state.releaseInputs.bundleDigest);assert.equal(state.releaseAllowed,true);assert.equal(state.mcpToolsExposed,true);});

test('signed cross-platform session control dynamically executes edit hold and finish',async()=>{const homeDir=await mkdtemp(path.join(os.tmpdir(),'diagram-control-'));const sessionId='11111111-1111-1111-1111-111111111111';let revision=0;let held=false;let finished=false;const control=await startSessionControl({sessionId,homeDir,onCommand:async(command,payload)=>{if(command==='edit'){assert.ok(Array.isArray(payload.operations));revision+=1;return {revision};}if(command==='hold'){held=true;return {sessionState:'idle_held'};}if(command==='finish'){finished=true;return {saved:true,sessionState:'stopped'};}throw new Error('unknown')}});try{const record={sessionId,controlEndpoint:control.endpoint,controlPublicKey:control.publicKey};assert.deepEqual(await callSessionControl(record,'edit',{operations:[{operation:'update',cell_id:'1',new_xml:'<mxCell/>'}]}),{revision:1});assert.equal((await callSessionControl(record,'hold')).sessionState,'idle_held');assert.equal((await callSessionControl(record,'finish',{mode:'save'})).saved,true);assert.equal(held,true);assert.equal(finished,true);}finally{await control.close();}});


test('release digest derives from deployed and npm-packed production inputs', async () => {
  assert.deepEqual(RELEASE_CONTROL_INPUTS,['package.json','lib/deploy.mjs']);
  const root=path.join(repo,'core/runtimes/drawio');const manifest=JSON.parse(await readFsFile(path.join(root,'manifest.json')));const closure=JSON.parse(await readFsFile(path.join(root,'dependency-lock.json')));const state=await computeReleaseInputState(repo,manifest,closure);
  for(const prefix of ['core/runtimes/drawio/','lib/diagram/'])assert.ok(Object.keys(state.digests).some(name=>name.startsWith(prefix)),prefix);
});

test('release digest is stable across verification evidence writes and changes on production input drift', async () => {
  const root=path.join(repo,'core/runtimes/drawio');const manifest=JSON.parse(await readFsFile(path.join(root,'manifest.json')));const closure=JSON.parse(await readFsFile(path.join(root,'dependency-lock.json')));
  const first=await computeReleaseInputState(repo,manifest,closure);const updated=structuredClone(manifest);updated.audit.releaseGate=!updated.audit.releaseGate;updated.audit.releaseVerificationState='verified';updated.audit.summary='verification narrative';updated.finalReleaseBlockers=[];for(const mitigation of updated.requiredMitigations??[]){mitigation.status='verified';mitigation.verifiedAt='2026-01-01T00:00:00Z';}updated.upstreamBehavior.networkBehavior.offlineCoreUiTrace='verified';delete updated.upstreamBehavior.networkBehavior.offlineCoreUiTraceReason;updated.offlineTrace={status:'verified',releaseInputDigest:first.bundleDigest};
  const second=await computeReleaseInputState(repo,updated,closure);assert.equal(second.bundleDigest,first.bundleDigest);assert.equal(second.traceBound,true);
  const temp=await mkdtemp(path.join(os.tmpdir(),'diagram-digest-drift-'));await import('node:fs/promises').then(({cp})=>cp(repo,temp,{recursive:true,filter:(src)=>!src.includes('/.git/')&&!src.includes('/node_modules/')}));await writeFile(path.join(temp,'lib/diagram/runtime.mjs'),(await readFsFile(path.join(temp,'lib/diagram/runtime.mjs'),'utf8'))+'\n// drift\n');
  const drift=await computeReleaseInputState(temp,manifest,closure);assert.notEqual(drift.bundleDigest,first.bundleDigest);await writeFile(path.join(temp,'core/runtimes/drawio/patches/unbound.mjs'),'export default 1');const added=await computeReleaseInputState(temp,manifest,closure);assert.notEqual(added.bundleDigest,drift.bundleDigest);await rm(temp,{recursive:true,force:true});
});

test('real production session worker launches fixed launcher, authenticates bridge, preserves UI edits and appends lifecycle history', async (t) => {
  const root=await mkdtemp(path.join(os.tmpdir(),'diagram-real-worker-'));
  const homeDir=path.join(root,'home'); const projectRoot=path.join(root,'project');await mkdir(projectRoot,{recursive:true});
  const packageRoot=path.join(root,'package');for(const name of ['cli.mjs','package.json','lib','core','adapters','templates','docs'])await cp(path.join(repo,name),path.join(packageRoot,name),{recursive:true});
  const manifestPath=path.join(packageRoot,'core/runtimes/drawio/manifest.json');const manifest=JSON.parse(await readFsFile(manifestPath));const closure=JSON.parse(await readFsFile(path.join(packageRoot,'core/runtimes/drawio/dependency-lock.json')));for(const mitigation of manifest.requiredMitigations??[])mitigation.status='verified';manifest.audit.releaseGate=true;manifest.audit.releaseVerificationState='verified';manifest.offlineTrace={...(manifest.offlineTrace??{}),status:'verified'};const prebound=await computeReleaseInputState(packageRoot,manifest,closure);manifest.offlineTrace.releaseInputDigest=prebound.bundleDigest;await writeFile(manifestPath,JSON.stringify(manifest,null,2));
  const cacheRoot=path.join(repo,'.cache/specline-diagram/archives');await mkdir(cacheRoot,{recursive:true});const download=async(artifact,destination)=>{const cache=path.join(cacheRoot,artifact.sha256);let bytes=await readFsFile(cache).catch(()=>null);if(!bytes){let response;for(let attempt=0;attempt<4;attempt++){try{response=await fetch(artifact.source,{signal:AbortSignal.timeout(120000)});if(response.ok)break}catch{}await new Promise(r=>setTimeout(r,500*2**attempt));}if(!response?.ok)throw new Error(`ARTIFACT_DOWNLOAD_FAILED:${artifact.id}`);bytes=Buffer.from(await response.arrayBuffer());if(createHash('sha256').update(bytes).digest('hex')!==artifact.sha256)throw new Error(`ARTIFACT_CHECKSUM_MISMATCH:${artifact.id}`);await writeFile(cache,bytes);}await writeFile(destination,bytes,{flag:'wx'});};
  const publicContext={packageRoot,homeDir,projectRoot,installRuntimeOptions:{safetyStage:'implementation-fixture',implementationFixtureRoot:root,download}};const planned=await runDiagramCommand(['plan','--action','install'],publicContext);assert.equal(planned.exitCode,0);assert.match(planned.body.state.planDigest,/^[a-f0-9]{64}$/);const installed=await runDiagramCommand(['install','--approved-plan',planned.body.state.planDigest],publicContext);assert.equal(installed.exitCode,0);const runtimeTarget=installed.body.state.target;
  const material=path.join(packageRoot,'core/runtimes/drawio/NOTICE.md');const originalMaterial=await readFsFile(material);await writeFile(material,Buffer.concat([originalMaterial,Buffer.from('\ndrift')]));const stale=await runDiagramCommand(['install','--approved-plan',planned.body.state.planDigest],publicContext);assert.equal(stale.body.code,'PLAN_STALE');await writeFile(material,originalMaterial);
  const worker=await startSessionWorker({project:projectRoot,slug:'production',purpose:'Architecture',audience:'Reviewers',confirmed:'["offline"]',assumptions:'["fixed runtime"]',openQuestions:'["none"]',workerProcessStartTime:'fixture-start'}, {homeDir,runtimeTarget,keepAlive:false,exit:()=>{},env:{...process.env,SPECLINE_DIAGRAM_IDLE_MS:'60000',SPECLINE_DIAGRAM_NO_BROWSER:'1'}}, manifest);
  t.after(async()=>{await worker.finish('discard').catch(()=>{});await rm(root,{recursive:true,force:true});});
  const anonymous=await fetch(worker.state.uiUrl);const anonymousHtml=await anonymous.text();assert.doesNotMatch(anonymousHtml,/bearer|token=/i);assert.doesNotMatch(worker.state.uiUrl,/token|bearer|bootstrap/i);
  assert.match(anonymousHtml,/script src="\/assets\/specline-bridge\.js"/);assert.match(anonymous.headers.get('content-security-policy')??'',/script-src 'self'/);assert.doesNotMatch(anonymous.headers.get('content-security-policy')??'',/unsafe-inline/);
  const bridgeScript=await fetch(new URL('/assets/specline-bridge.js',worker.state.uiUrl)).then(r=>r.text());assert.match(bridgeScript,/event\.source!==frame\.contentWindow/);assert.doesNotMatch(bridgeScript,/Bearer|token=/i);
  const {chromium}=await import('playwright');
  const chromeTesting=path.join(os.homedir(),'Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
  const browser=await chromium.launch({headless:true, executablePath: process.env.SPECLINE_PLAYWRIGHT_CHROME || chromeTesting});const browserContext=await browser.newContext();const browserPage=await browserContext.newPage();const bootResponse=await browserPage.goto(worker.bootstrapUrl,{waitUntil:'domcontentloaded',timeout:30000});assert.equal(bootResponse.status(),200);assert.equal(browserPage.url(),worker.state.uiUrl);const authCookie=(await browserContext.cookies()).find(value=>value.name==='specline-diagram');assert.equal(authCookie?.httpOnly,true);assert.equal(authCookie?.sameSite,'Strict');assert.equal(authCookie?.path,`/api/sessions/${worker.state.sessionId}/`);const cookie=`specline-diagram=${authCookie.value}`;const replay=await fetch(worker.bootstrapUrl,{redirect:'manual'});assert.equal(replay.status,410);await browserPage.waitForSelector('#drawio',{state:'attached',timeout:20000});await browserPage.waitForFunction(()=>typeof window.speclineBridge==='function',null,{timeout:20000});const frameResponse=await browserContext.request.get(new URL('/assets/index.html?embed=1&proto=json&spin=1&offline=1',worker.state.uiUrl).href);assert.equal(frameResponse.status(),200);const frameHtml=await frameResponse.text();assert.match(frameHtml,/draw\.io|diagrams\.net/i);const frameElement=await browserPage.waitForSelector('#drawio');await browserPage.waitForTimeout(3000);const drawioFrame=await frameElement.contentFrame();assert.ok(drawioFrame);assert.equal(drawioFrame.url().startsWith('chrome-error:'),false);assert.match(drawioFrame.url(),/assets\/index\.html/);
const record=JSON.parse(await readFsFile(path.join(homeDir,'.specline/runtimes/drawio/sessions',`${worker.state.sessionId}.json`)));
  assert.equal(record.workerParentPid,process.ppid); assert.equal(record.workerProcessStartTime,'fixture-start');
  const initial=await callSessionControl(record,'readState');const marker=`NATIVE-EDITOR-${Date.now()}`;
  const origin=new URL(worker.state.uiUrl).origin; const endpoint=new URL(`/api/sessions/${worker.state.sessionId}/state`,origin);
  const unauthenticated=await fetch(endpoint,{headers:{origin}});assert.equal(unauthenticated.status,401);
  const wrongOrigin=await fetch(endpoint,{headers:{cookie,origin:'http://127.0.0.1:9'}});assert.equal(wrongOrigin.status,403);
  const wrongSession=await fetch(new URL('/api/sessions/wrong/state',origin),{headers:{cookie,origin}});assert.equal(wrongSession.status,403);
  await drawioFrame.waitForFunction(()=>window.speclineDrawioEditorUi?.editor?.graph,{timeout:30000});const nativeModel=await drawioFrame.evaluate(value=>{const ui=window.speclineDrawioEditorUi,graph=ui.editor.graph,parent=graph.getDefaultParent();graph.getModel().beginUpdate();try{graph.insertVertex(parent,null,value,120,120,180,60);}finally{graph.getModel().endUpdate();}ui.actions.get('save').funct();return graph.getModel().getDescendants(parent).some(cell=>cell.value===value);},marker);assert.equal(nativeModel,true);await browserPage.waitForFunction(value=>window.speclineBridge('state').then(state=>state.xml.includes(value)),marker,{timeout:15000});await browserPage.waitForFunction(()=>window.speclineLastDrawioEvent?.event==='save',{timeout:15000});const edited=await browserPage.evaluate(()=>window.speclineBridge('state'));assert.match(edited.xml,new RegExp(marker));await browserPage.evaluate(()=>document.querySelector('#drawio').contentWindow.postMessage(JSON.stringify({action:'export',format:'xml'}),location.origin));await browserPage.waitForFunction(()=>window.speclineLastDrawioEvent?.event==='export'&&window.speclineLastDrawioEvent?.format==='xml',{timeout:15000});
  const synced=await callSessionControl(record,'readState'); assert.ok(synced.revision>=edited.revision);assert.match((await browserPage.evaluate(()=>window.speclineBridge('state'))).xml,new RegExp(marker));
  const exported=await callSessionControl(record,'export',{baseRevision:synced.revision,format:'drawio'}); assert.match(exported.exportRelativePath,/production\.drawio$/);const svg=await callSessionControl(record,'export',{baseRevision:synced.revision,format:'svg'});assert.match(svg.exportRelativePath,/production\.svg$/);assert.match(await readFsFile(path.join(projectRoot,svg.exportRelativePath),'utf8'),new RegExp(marker));
  const held=await callSessionControl(record,'hold'); assert.equal(held.sessionState,'idle_held'); assert.ok(held.holdUntil);
  await new Promise((resolve)=>setTimeout(resolve,40)); await callSessionControl(record,'readState');
  const refreshed=JSON.parse(await readFsFile(path.join(homeDir,'.specline/runtimes/drawio/sessions',`${worker.state.sessionId}.json`))); assert.ok(Date.parse(refreshed.holdUntil)>Date.parse(held.holdUntil));
  await browserContext.close();await browser.close();const controlEndpoint=record.controlEndpoint;const finished=await callSessionControl(record,'finish',{mode:'save'}); assert.equal(finished.saved,true);const finishedAgain=await worker.finish('save');assert.equal(finishedAgain.saved,finished.saved);
  await new Promise((resolve)=>setTimeout(resolve,30));assert.equal(await stat(controlEndpoint).then(()=>true,()=>false),false);await assert.rejects(fetch(worker.state.uiUrl,{signal:AbortSignal.timeout(1000)}));
  const drawio=await readFsFile(path.join(projectRoot,'specline/diagrams/production/production.drawio'),'utf8'); assert.match(drawio,new RegExp(marker));
  const markdown=await readFsFile(path.join(projectRoot,'specline/diagrams/production/production.md'),'utf8');
  await new Promise((resolve)=>setTimeout(resolve,50));
  for(const value of ['Architecture','Reviewers','offline','fixed runtime','edit','export drawio','finish save','save']) assert.match(markdown,new RegExp(value));
  assert.ok((markdown.match(/^- /gm)||[]).length>=4);
  const cliChild=spawn(process.execPath,[path.join(packageRoot,'cli.mjs'),'diagram','session-worker','--project',projectRoot,'--slug','cli-child','--worker-process-start-time',String(Date.now())],{env:{...process.env,HOME:homeDir,SPECLINE_DIAGRAM_NO_BROWSER:'1'},stdio:['ignore','ignore','ignore','ipc']});const ready=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('CLI worker startup timeout')),15000);cliChild.once('message',message=>{clearTimeout(timer);resolve(message)});cliChild.once('error',reject);cliChild.once('exit',code=>reject(new Error(`CLI worker exited early ${code}`)));});const cliRecord=JSON.parse(await readFsFile(path.join(homeDir,'.specline/runtimes/drawio/sessions',`${ready.state.sessionId}.json`)));await callSessionControl(cliRecord,'finish',{mode:'discard'});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('CLI worker did not exit')),15000);cliChild.once('exit',()=>{clearTimeout(timer);resolve()})});assert.equal(await stat(cliRecord.controlEndpoint).then(()=>true,()=>false),false);await assert.rejects(fetch(cliRecord.uiUrl,{signal:AbortSignal.timeout(1000)}));assert.throws(()=>process.kill(cliChild.pid,0));
});
